name: Deploy to InfinityFree

on:
  push:
    branches:
      - main # main branch ထဲ push လုပ်ရင် အလုပ်လုပ်မယ်

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/testcicd # InfinityFree ရဲ့ public folder လမ်းကြောင်း